const Leads = [
    {
      id: 6,
      firstName: "Michael",
      lastName: "Thompson",
      companyName: "CloudTech Solutions",
      linkedinProfile: "https://linkedin.com/in/michaelthompson",
      jobTitle: "Cloud Architecture Director",
      emailAddress: "michael.thompson@cloudtech.com",
      phoneNumber: "+1 (555) 678-9012",
    },
    {
      id: 7,
      firstName: "Aisha",
      lastName: "Patel",
      companyName: "HealthInnovate Inc.",
      linkedinProfile: "https://linkedin.com/in/aishapatel",
      jobTitle: "Healthcare Innovation Lead",
      emailAddress: "aisha.patel@healthinnovate.com",
      phoneNumber: "+1 (555) 789-0123",
    },
    {
      id: 8,
      firstName: "Carlos",
      lastName: "Mendoza",
      companyName: "GlobalLogistics Network",
      linkedinProfile: "https://linkedin.com/in/carlosmendoza",
      jobTitle: "Supply Chain Manager",
      emailAddress: "carlos.mendoza@globallogistics.com",
      phoneNumber: "+1 (555) 890-1234",
    },
    {
      id: 9,
      firstName: "Elena",
      lastName: "Volkova",
      companyName: "CyberSecure Solutions",
      linkedinProfile: "https://linkedin.com/in/elenavolkova",
      jobTitle: "Cybersecurity Strategist",
      emailAddress: "elena.volkova@cybersecure.com",
      phoneNumber: "+1 (555) 901-2345",
    },
    {
      id: 10,
      firstName: "Ryan",
      lastName: "Kim",
      companyName: "GreenTech Innovations",
      linkedinProfile: "https://linkedin.com/in/ryankim",
      jobTitle: "Renewable Energy Engineer",
      emailAddress: "ryan.kim@greentech.com",
      phoneNumber: "+1 (555) 012-3456",
    },
    {
      id: 11,
      firstName: "Isabella",
      lastName: "Garcia",
      companyName: "MarketPulse Analytics",
      linkedinProfile: "https://linkedin.com/in/isabellagarcia",
      jobTitle: "Market Research Director",
      emailAddress: "isabella.garcia@marketpulse.com",
      phoneNumber: "+1 (555) 234-5678",
    },
    {
      id: 12,
      firstName: "David",
      lastName: "Nakamura",
      companyName: "RoboTech Dynamics",
      linkedinProfile: "https://linkedin.com/in/davidnakamura",
      jobTitle: "Robotics Engineering Manager",
      emailAddress: "david.nakamura@robotech.com",
      phoneNumber: "+1 (555) 345-6789",
    },
    {
      id: 13,
      firstName: "Olivia",
      lastName: "Williams",
      companyName: "FinanceForward Group",
      linkedinProfile: "https://linkedin.com/in/oliviawilliams",
      jobTitle: "Financial Strategy Consultant",
      emailAddress: "olivia.williams@financeforward.com",
      phoneNumber: "+1 (555) 456-7890",
    },
    {
      id: 14,
      firstName: "Mohammed",
      lastName: "Abdullah",
      companyName: "GlobalEd Technologies",
      linkedinProfile: "https://linkedin.com/in/mohammedabdullah",
      jobTitle: "EdTech Innovation Lead",
      emailAddress: "mohammed.abdullah@globaled.com",
      phoneNumber: "+1 (555) 567-8901",
    },
    {
      id: 15,
      firstName: "Sarah",
      lastName: "Mitchell",
      companyName: "AIQuest Research",
      linkedinProfile: "https://linkedin.com/in/sarahmitchell",
      jobTitle: "Artificial Intelligence Researcher",
      emailAddress: "sarah.mitchell@aiquest.com",
      phoneNumber: "+1 (555) 678-9012",
    },
    {
        id: 1,
        firstName: "John",
        lastName: "Doe",
        companyName: "Tech Innovations Inc.",
        linkedinProfile: "https://linkedin.com/in/johndoe",
        jobTitle: "Sales Manager",
        emailAddress: "john.doe@techinnovations.com",
        phoneNumber: "+1 (555) 123-4567",
      },
      {
        id: 2,
        firstName: "Sophia",
        lastName: "Smith",
        companyName: "Global Solutions Ltd.",
        linkedinProfile: "https://linkedin.com/in/sophiasmith",
        jobTitle: "Marketing Director",
        emailAddress: "sophia.smith@globalsolutions.com",
        phoneNumber: "+1 (555) 234-5678",
      },
      {
        id: 3,
        firstName: "Liam",
        lastName: "Brown",
        companyName: "NextGen Tech",
        linkedinProfile: "https://linkedin.com/in/liambrown",
        jobTitle: "Software Engineer",
        emailAddress: "liam.brown@nextgen.com",
        phoneNumber: "+1 (555) 345-6789",
      },
      {
        id: 4,
        firstName: "Emma",
        lastName: "Rodriguez",
        companyName: "Green Energy Solutions",
        linkedinProfile: "https://linkedin.com/in/emmarodriguez",
        jobTitle: "Sustainability Manager",
        emailAddress: "emma.rodriguez@greenenergy.com",
        phoneNumber: "+1 (555) 456-7890",
      },
      {
        id: 5,
        firstName: "Alexander",
        lastName: "Chen",
        companyName: "DataDrive Analytics",
        linkedinProfile: "https://linkedin.com/in/alexanderchen",
        jobTitle: "Data Science Lead",
        emailAddress: "alexander.chen@datadrive.com",
        phoneNumber: "+1 (555) 567-8901",
      }
  ];
  
  export default Leads;